Repository GameTactic/CPP-Echo, pull requests merged in 2019-10, with the labels that each got.

#8 Ensure object lifetime of srv is started.
  src/main.cpp
Labels: enhancement, hacktoberfest

#10 Make signal handler safe.
  src/main.cpp
Labels: enhancement, hacktoberfest

#11 Make signal handler safe.
  src/main.cpp
Labels: enhancement, hacktoberfest

#16 Add Loki Astari to credits
  README.md
Labels: documentation, enhancement

#15 Fix application not dying.
  src/main.cpp
Labels: bug, enhancement, help wanted
